# Generated by Django 5.2.8 on 2025-11-26 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('minimum_quantity', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('Input', 'Input'), ('Output', 'Output')], max_length=50)),
                ('operation_date', models.DateTimeField(auto_now_add=True)),
                ('quantity_moved', models.IntegerField()),
                ('movement_responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
