# Generated by Django 5.2.8 on 2025-11-27 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_current_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='historical_records', to='api.product'),
            preserve_default=False,
        ),
    ]
