# Generated by Django 5.0.6 on 2025-11-27 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_historical_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_records', to='api.product'),
        ),
    ]
