# Generated by Django 5.2.8 on 2025-11-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
