# Generated by Django 5.0.6 on 2025-11-27 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_historical_movement_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_records', to='api.product'),
        ),
    ]
